sonar.projectKey=connexa-contact-management
sonar.projectName=Connexa Contact Management
sonar.projectVersion=1.0
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.java.binaries=backend/target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
