spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=connexa
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

logging.level.org.springframework=INFO
logging.level.com.connexa=DEBUG
